Shooter code
SaintsRobotics/OffSeasonIR2021 pull request #1
Opened 2021-07-15 01:22 UTC by ProgrammingSR

2021-07-15 01:42 UTC, noam987 requested changes
2 simple minor changes to clean it up, but overall great

2021-07-15 01:42 UTC, noam987 commented on src/main/java/frc/robot/HardwareMap.java
> +        public CANSparkMax leftShooter = new CANSparkMax(16, MotorType.kBrushless);
move the construction of objects into the constructor of shooter hardware. (the new CANSparkmax part)

2021-07-15 01:42 UTC, noam987 commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +    m_shooter = shooter.shooter;
why are you taking in both motors if you don't use them.

2021-07-15 01:59 UTC, ProgrammingSR commented
Needs to work on bang bang loop

2021-07-15 03:57 UTC, noam987 commented
Consider doing it in two parts. Get the base code in first, add bang bang in the next PR

2021-07-25 23:55 UTC, noam987 approved these changes
I approve but have someone else also review it. Does Shoot one ball command need to be merged now?

2021-07-26 04:16 UTC, noam987 approved these changes

2021-07-26 20:35 UTC, thetaspirit requested changes

2021-07-26 20:35 UTC, thetaspirit commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +  private CANEncoder m_canEncoder;
Please rename this

2021-07-26 20:35 UTC, thetaspirit commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +  public void setShooter(double speed){
The following methods need javadocs.  Writing a javadoc for `periodic` is up to you.

2021-07-26 20:35 UTC, thetaspirit commented on src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +  public ShooterSubsystem(ShooterHardware shooter) {
Please also briefly explain the distinction between the shooter and feeder in javadocs for this constructor.  Also rename `m_canEncoder` and briefly describe its purpose.

2021-07-27 00:51 UTC, TiaSinghania approved these changes
javadocs need to be added but that can be done with a seperate PR

2021-07-27 01:28 UTC, merged