Climber code
SaintsRobotics/OffSeasonIR2021 pull request #12
Opened 2021-08-12 02:23 UTC by Skipppyyy

PR by Vismay, Aaryan, and Kanav

looks mucho good to us

2021-08-16 02:20 UTC, TiaSinghania approved these changes
I think we could do one more comprehensive test before merging, just to be sure, but this looks good

2021-08-17 20:50 UTC, Skipppyyy commented on src/main/java/frc/robot/RobotContainer.java
> +
Changes from yesterday were never pushed

2021-08-19 15:20 UTC, LennyAbbas requested changes
There's a lot of small problems with this PR. I could have changed them myself but then you'd make all the same mistakes next time..

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/Constants.java
> +        public static final double CLIMBER_CONTROL_SPEED_DEADZONE = 0.2;
These should have javadocs

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/Constants.java
> +        public static final double CLIMBER_CONTROL_SPEED_DEADZONE = 0.2;
how is CLIMBER_CONTROL_SPEED more descriptive than CLIMBER_SPEED?

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/HardwareMap.java
> +            frontLeftDriveMotor = new CANSparkMax(Constants.SwervePorts.FRONT_LEFT_DRIVE_MOTOR_PORT,
formatting SwerveModuleHardware is outside the scope of this PR

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/HardwareMap.java
> +                armController.setNeutralMode(NeutralMode.Brake);
why is this in this PR

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/HardwareMap.java
> +        public CANSparkMax winchMotor;
these need javadoc descriptions

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/HardwareMap.java
> +            servoMotor = new Servo(Constants.ClimberPorts.SERVO_MOTOR_PORT);
```suggestion
            servoMotor = new Servo(ClimberPorts.SERVO_MOTOR_PORT);
```

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/Robot.java
> +   * This method is called periodically.
Why has this been changed?

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/RobotContainer.java
> +import edu.wpi.first.wpilibj.XboxController.Axis;
```suggestion

```

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/RobotContainer.java
> +import edu.wpi.first.wpilibj.GenericHID.Hand;
```suggestion
import edu.wpi.first.wpilibj.GenericHID.Hand;
import edu.wpi.first.wpilibj.XboxController;
```
reorder to be alphabetical

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/RobotContainer.java
>  import frc.robot.commands.SwerveJoystickCommand;
```suggestion
import frc.robot.commands.SwerveJoystickCommand;
import frc.robot.subsystems.ClimberSubsystem;
```
reoreder to be alphabetical

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/RobotContainer.java
> +      m_operatorController);
this should be constructed inline

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/RobotContainer.java
> +    m_climberSubsystem.setDefaultCommand(m_climberControllerCommand);
why is this in a different order than what you constructed them in?

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/RobotContainer.java
> +       .whenPressed(new ShooterOnCommand(m_shooterSubsystem));
formatting this is outside the scope of the PR
```suggestion
        .whenPressed(new ShooterOnCommand(m_shooterSubsystem));
```

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/RobotContainer.java
> +       .whenPressed(new ShooterOffCommand(m_shooterSubsystem));
```suggestion
        .whenPressed(new ShooterOffCommand(m_shooterSubsystem));
```

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/RobotContainer.java
> +    new Trigger(()-> m_operatorController.getTriggerAxis(Hand.kLeft) > 0.5)
change type from Trigger to Button

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/RobotContainer.java
> +    // releases the Climber when Start is pressed
clarify what controller because start button resets the gyro on the drive controller

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/RobotContainer.java
> +    // Sets brake and coast mode with left bumper
this should be in a different PR

2021-08-19 15:20 UTC, LeonardAbbas commented on src/main/java/frc/robot/RobotContainer.java
> +
why?
```suggestion
```

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/commands/ClimberControllerCommand.java
> +
needs to be overridden same with the isFinished method

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/commands/ClimberControllerCommand.java
> +public class ClimberControllerCommand extends CommandBase{
this class could be constructed in line using a runCommand

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/commands/ClimberControllerCommand.java
> +    }
this method is not necessary

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/commands/SwerveJoystickCommand.java
> +        * Constants.SwerveConstants.MAX_SPEED_METERS_PER_SECOND * 0.2;
why was SwerveJoystickCommand changed?

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +//import com.revrobotics.CANSparkMaxLowLevel.MotorType;
commented out code

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +import frc.robot.HardwareMap.ClimberHardware;
imports need to be organized

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +
```suggestion
```

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +   * @return
no description for what it returns

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +   * The Angle of the Servo that releases the climber
```suggestion
   * Returns the angle of the servo that releases the climber.
```

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +   */
this javadoc is not clear

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +    m_ratchetServo.set(Constants.ClimberConstants.WINCH_REVERSE_SERVO_POSITION);
```suggestion
    m_ratchetServo.set(ClimberConstants.WINCH_REVERSE_SERVO_POSITION);
```

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +    DriverStation.reportError("climb direction reversed", false);
are these print statements really necessary, there's already way too many

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +   *
bad javadoc

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +
```suggestion
```

2021-08-19 15:20 UTC, LennyAbbas commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +    SmartDashboard.putNumber("Intake Motor Speed", m_desiredIntakeSpeed);
why was IntakeSubsystem changed

2021-08-22 00:01 UTC, TiaSinghania commented on src/main/java/frc/robot/HardwareMap.java
> +            frontLeftDriveMotor = new CANSparkMax(Constants.SwervePorts.FRONT_LEFT_DRIVE_MOTOR_PORT,
yeah but it's been done anyway so it's fine

2021-08-22 00:02 UTC, TiaSinghania commented on src/main/java/frc/robot/HardwareMap.java
> +                armController.setNeutralMode(NeutralMode.Brake);
to keep the arm up - addressed in slack

2021-08-22 00:09 UTC, TiaSinghania commented on src/main/java/frc/robot/HardwareMap.java
> +            servoMotor = new Servo(Constants.ClimberPorts.SERVO_MOTOR_PORT);
for the sake of consistency i won't change this right now. we can fix it in a new PR to clean up later

2021-08-24 02:57 UTC, merged