Operator board controls
SaintsRobotics/OffSeasonIR2021 pull request #17
Opened 2021-09-14 15:02 UTC by TiaSinghania

implementation for the op board, reorganized some files

2021-09-14 16:30 UTC, TiaSinghania commented on src/main/java/frc/robot/commands/ReleaseRatchetCommand.java
> +    m_subsystem.lockRatchet();
why are we locking the ratchet after releasing it? don't we want to extend the arm further?

2021-09-14 16:34 UTC, TiaSinghania reviewed
overall seems good, but why do we lock the ratchet after releasing the climber?

2021-09-17 23:18 UTC, dbzfan2012 commented on src/main/java/frc/robot/OperatorBoard.java
>      public OperatorBoardButton BUTTON_TWELVE;
Delaynie says change this to private because the button does not have a function

2021-09-17 23:32 UTC, dbzfan2012 commented on src/main/java/frc/robot/RobotContainer.java
> +                new JoystickButton(m_driveController, Button.kA.value)
Add a comment for vision aiming

2021-09-17 23:34 UTC, dbzfan2012 commented on src/main/java/frc/robot/commands/FeederCommand.java
>  /** Command to shoot one ball. */
javadoc should be updated since shootoneballcommand was replaced with feedercommand

2021-09-17 23:40 UTC, dbzfan2012 commented on src/main/java/frc/robot/commands/FeederCommand.java
> -    addRequirements(m_shooterSubsystem);
the addRequirements() should not have been removed

2021-09-18 00:03 UTC, dbzfan2012 requested changes
Neel and Ethan K - Added a few comments for things to be fixed

2021-09-18 04:52 UTC, merged